# name: Flutter_Web

# on:
#   push:
#     branches: [ master ]
#     paths-ignore:
#       - '**/README.md'
#   pull_request:
#     branches: [ master ]
#     paths-ignore:
#       - '**/README.md'

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false
#       - name: Build ğŸ”§ 
#         uses: subosito/flutter-action@v1
#         with:
#           channel: beta
#       - run: |
#             flutter config --enable-web
#             flutter pub get
#             flutter test
#             flutter build web --web-renderer canvaskit
#       # https://github.com/flutter/flutter/issues/69760
#       - name: Post Build ğŸ›¸
#         run: |
#             sed -i 's/<base href="\/">/<base href="\/flutter-pos\/">/g' ./build/web/index.html
#             cat ./build/web/index.html
#       - name: Deploy ğŸš€
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./build/web
##################For BOth Android and Ios ???####################
# make sure <in pubspec.yaml> you have your sdk version as per subosito/flutter-action, and also enerating token for workflow < Secret token github>
# on:
#   pull_request:
#     branches:
#       - main
#       - master
#   push:
#     branches:
#       - main
#       - master
#       - develop
# name: "Build & Release"
# jobs:
#   build:
#     name: Build & Release
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12.x'
#       - uses: subosito/flutter-action@v1
#         with:
#           flutter-version: '2.2.0'
#       - run: flutter pub get
#       - run: flutter test
#       - run: flutter build apk --debug --split-per-abi
#       - run: |
#           flutter build ios --no-codesign
#           cd build/ios/iphoneos
#           mkdir Payload
#           cd Payload
#           ln -s ../Runner.app
#           cd ..
#           zip -r app.ipa Payload
#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
#           tag: v1.0.${{ github.run_number }}
#           token: ${{ secrets.TOKEN }}

############################################################FOR ANDROID ###########################3 todo change flutterenvironment:
  # sdk: '>=2.19.0-154.0.dev <3.0.0' to sdk: '>=2.17.6 <3.0.0'
  on:
    pull_request:
      branches:
      # you can add more branches 
        - main
        - master
        - base
        - advanced
        - nobug
        - auth
        - mod
        - mode
        - starter
    push:
      branches:
      # you can add more branches 
        - main
        - master
        - develop
        - base 
        - advanced
        - nobug
        - auth
        - mod
        - mode
        - starter
  
  name: "Build & Release"
  jobs:
    build:
      name: Build & Release
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v1
          with:
            java-version: '12.x'
            # you can change subosito/flutter-action@version as per your choice 
        - uses: subosito/flutter-action@v2
          with:
          # you can change flutter-version: as per subosito/flutter-action@version as per your choice 
            flutter-version: '3.3.5'
            # channel: 'stable'
        - run: flutter --version
        - run: flutter pub get
        # - run: flutter gen-l10n
  
        # you can even build aab or ipa as per your command but remember you need to change the relese code for  artifacts:  directory
        - run: flutter build apk --release --split-per-abi
        - name: Push to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/flutter-apk/*"
            tag: v1.0.${{ github.run_number }}
            token: ${{ secrets.TOKEN }} # remember you have added the Secrets token in your repo with the same name as TOKEN and add that generated token <Github Secrate token> in value field 
  # ###############################################FOR IOS ONLY#############################################
  # on:
  #   pull_request:
  #     branches:
  #       - main
  #       - master
  #   push:
  #     branches:
  #       - main
  #       - master
  #       - develop
  # name: "Build & Release"
  # jobs:
  #   build:
  #     name: Build & Release
  #     runs-on: macos-latest
  #     steps:
  #       - uses: actions/checkout@v1
  #       - uses: actions/setup-java@v1
  #         with:
  #           java-version: '12.x'
  #       - uses: subosito/flutter-action@v1
  #         with:
  #           flutter-version: '2.2.0'
  #       - run: flutter pub get
  #       - run: flutter test
  #       - run: |
  #           flutter build ios --no-codesign
  #           cd build/ios/iphoneos
  #           mkdir Payload
  #           cd Payload
  #           ln -s ../Runner.app
  #           cd ..
  #           zip -r app.ipa Payload
  #       - name: Push to Releases
  #         uses: ncipollo/release-action@v1
  #         with:
  #           artifacts: "build/ios/iphoneos/app.ipa"
  #           tag: v1.0.${{ github.run_number }}
  #           token: ${{ secrets.TOKEN }}  
